services:
  nginx:
    container_name: skillbox-quiz-nginx
    build:
      context: ./client
      target: quiz_nginx
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true