services:
  nginx:
    container_name: skillbox-quiz-nginx
    build:
      context: ./client
      target: quiz_nginx
    networks:
      - traefik-network
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.quiz-frontend.rule=Host(`quiz.skillbox.by`) && PathPrefix(`/`)"
     - "traefik.http.routers.quiz-frontend.entrypoints=https"
     - "traefik.http.routers.quiz-frontend.tls.certresolver=le"
     - "traefik.http.services.quiz-frontend.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
